name: clinic-booking

services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: clinic
      POSTGRES_PASSWORD: clinic
      POSTGRES_DB: clinic
    ports:
      - "${POSTGRES_HOST_PORT:-5432}:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U clinic -d clinic"]
      interval: 5s
      timeout: 5s
      retries: 10

  redis:
    image: redis:7-alpine
    ports:
      - "${REDIS_HOST_PORT:-6379}:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 10

  redis-insight:
    image: redislabs/redisinsight:2.66
    container_name: redis-insight
    ports:
      - "8001:5540"
    environment:
      REDIS_PORT: 6379
      REDIS_HOST: redis
    depends_on:
      - redis

volumes:
  pgdata:
